[2024-01-08T09:15:04.960+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: fetching_cleaning.Fetch_from_Postgresql manual__2024-01-08T09:15:02.877651+00:00 [queued]>
[2024-01-08T09:15:04.966+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: fetching_cleaning.Fetch_from_Postgresql manual__2024-01-08T09:15:02.877651+00:00 [queued]>
[2024-01-08T09:15:04.966+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2024-01-08T09:15:04.966+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 2
[2024-01-08T09:15:04.966+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2024-01-08T09:15:04.973+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): Fetch_from_Postgresql> on 2024-01-08 09:15:02.877651+00:00
[2024-01-08T09:15:04.985+0000] {standard_task_runner.py:52} INFO - Started process 714 to run task
[2024-01-08T09:15:04.988+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fetching_cleaning', 'Fetch_from_Postgresql', 'manual__2024-01-08T09:15:02.877651+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmp25yl1f3l', '--error-file', '/tmp/tmpn1pdzaoh']
[2024-01-08T09:15:04.991+0000] {standard_task_runner.py:80} INFO - Job 11: Subtask Fetch_from_Postgresql
[2024-01-08T09:15:05.209+0000] {task_command.py:371} INFO - Running <TaskInstance: fetching_cleaning.Fetch_from_Postgresql manual__2024-01-08T09:15:02.877651+00:00 [running]> on host 13eafc15112b
[2024-01-08T09:15:05.327+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=saepul
AIRFLOW_CTX_DAG_ID=fetching_cleaning
AIRFLOW_CTX_TASK_ID=Fetch_from_Postgresql
AIRFLOW_CTX_EXECUTION_DATE=2024-01-08T09:15:02.877651+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-08T09:15:02.877651+00:00
[2024-01-08T09:15:05.572+0000] {python.py:173} INFO - Done. Returned value was: None
[2024-01-08T09:15:05.592+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=fetching_cleaning, task_id=Fetch_from_Postgresql, execution_date=20240108T091502, start_date=20240108T091504, end_date=20240108T091505
[2024-01-08T09:15:05.651+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-01-08T09:15:05.683+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
