[2024-01-08T08:38:05.243+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: fetching_cleaning.Fetch_from_Postgresql manual__2024-01-08T08:38:03.459400+00:00 [queued]>
[2024-01-08T08:38:05.250+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: fetching_cleaning.Fetch_from_Postgresql manual__2024-01-08T08:38:03.459400+00:00 [queued]>
[2024-01-08T08:38:05.250+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2024-01-08T08:38:05.251+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 2
[2024-01-08T08:38:05.251+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2024-01-08T08:38:05.260+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): Fetch_from_Postgresql> on 2024-01-08 08:38:03.459400+00:00
[2024-01-08T08:38:05.267+0000] {standard_task_runner.py:52} INFO - Started process 258 to run task
[2024-01-08T08:38:05.270+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fetching_cleaning', 'Fetch_from_Postgresql', 'manual__2024-01-08T08:38:03.459400+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpp1fofc2c', '--error-file', '/tmp/tmpor72blnt']
[2024-01-08T08:38:05.273+0000] {standard_task_runner.py:80} INFO - Job 3: Subtask Fetch_from_Postgresql
[2024-01-08T08:38:05.388+0000] {task_command.py:371} INFO - Running <TaskInstance: fetching_cleaning.Fetch_from_Postgresql manual__2024-01-08T08:38:03.459400+00:00 [running]> on host 13eafc15112b
[2024-01-08T08:38:05.440+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=saepul
AIRFLOW_CTX_DAG_ID=fetching_cleaning
AIRFLOW_CTX_TASK_ID=Fetch_from_Postgresql
AIRFLOW_CTX_EXECUTION_DATE=2024-01-08T08:38:03.459400+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-08T08:38:03.459400+00:00
[2024-01-08T08:38:05.556+0000] {python.py:173} INFO - Done. Returned value was: None
[2024-01-08T08:38:05.574+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=fetching_cleaning, task_id=Fetch_from_Postgresql, execution_date=20240108T083803, start_date=20240108T083805, end_date=20240108T083805
[2024-01-08T08:38:05.607+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-01-08T08:38:05.642+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
